# -*- coding: utf-8 -*-
# Copyright (c) 2026 yaqiang.sun.
# This source code is licensed under the license found in the LICENSE file
# in the root directory of this source tree.
#########################################################################
# Author: yaqiangsun
# Created Time: 2026/04/21 13:21:03
########################################################################

# -*- coding: utf-8 -*-
# Copyright (c) 2025 yaqiang.sun.
# This source code is licensed under the license found in the LICENSE file
# in the root directory of this source tree.
#########################################################################
# Author: yaqiangsun
# Created Time: 2025/10/20 18:13:37
########################################################################


import os

import numpy as np
import sys
# 获取当前文件的绝对路径，向上两层就是项目根目录
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if project_root not in sys.path:
    sys.path.insert(0, project_root)
# 
# `scope_api_client`: this package is generated by `openapi-python-client`

from .task import run_task
from .postprocess import run_postprocess
from qubitclient.utils.env_load import get_config

import logging



logging.basicConfig(level=logging.INFO)


class QubitNNScopeClient(object):
    def __init__(self, url=None, api_key=None):
        # 使用配置加载器获取配置（支持多种来源和优先级）
        config = get_config(url=url, api_key=api_key)
        self.url = config['url']
        self.api_key = config['api_key']

    def request(self, file_list:list[str|dict[str,np.ndarray]|np.ndarray],task_type:str="s21peak",*args,**kwargs):
        if len(file_list)>0:
            response = run_task(file_list=file_list,url=self.url,api_key=self.api_key,task_type=task_type,*args,**kwargs)
        else:
            raise ValueError("file_list must not be empty")
        return response
    def get_result(self,response):
        if response.status_code == 200:
            logging.debug("Result: %s", response.json())
            result = response.json()
            # result = result["result"]
            if "result" in result.keys():
                result["results"] = result["result"] # add results keys
            elif "results" in result.keys(): # add result keys
                result["result"] = result["results"]
            return result
        else:
            logging.error("Error: %s %s", response.status_code, response.text)
            return []
    def get_filtered_result(self, response, threshold, task_type: str = "s21peak"):
        result = run_postprocess(response, threshold, task_type)
        if "result" in result.keys():
            result["results"] = result["result"]
        elif "results" in result.keys():
            result["result"] = result["results"]
        return result