version: '3.8'

services:
  proxy:
    image: yaqiangsun/proxy:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "9801:8000"
    volumes:
      - ./proxy/config:/app/config
      - ./tmp:/app/tmp

  qubitserving:
    image: ghcr.io/yaqiangsun/qubitserving:latest
    restart: unless-stopped
    ports:
      - "9000:8000"
    volumes:
      - ./qubitserving/license/license.json:/app/license/license.json
      - ./qubitserving/model_zoo:/app/model_zoo
      - ./tmp:/app/tmp
      - /sys:/sys:ro
      - /etc:/etc:ro
    cap_add:
      - NET_ADMIN

  qubitscope:
    image: ghcr.io/yaqiangsun/qubitscope:latest
    restart: unless-stopped
    ports:
      - "9001:8000"
    volumes:
      - ./qubitscope/license/license.json:/fba/license/license.json
      - /sys:/sys:ro
      - /etc:/etc:ro
    cap_add:
      - NET_ADMIN