version: '3.8'

services:
  qubitscope:
    image: yaqiangsun/qubitscope:latest
    restart: unless-stopped
    ports:
      - "9001:8000"
    volumes:
      - ./license/license.json:/fba/license/license.json