version: '3.8'

services:
  qubitserving:
    image: ghcr.io/yaqiangsun/qubitserving:latest
    restart: unless-stopped
    ports:
      - "9000:8000"
    volumes:
      - ./license/license.json:/app/license/license.json
      - ./model_zoo:/app/model_zoo
      - ./tmp:/app/tmp
      - /sys:/sys:ro
      - /etc:/etc:ro
    cap_add:
      - NET_ADMIN